const Constants = {
    CREATE_REPORT: "CREATE_REPORT",
    FULL_DIALOG: "FULL_DIALOG",
    FULL_DIALOG_OPEN: "FULL_DIALOG_OPEN",
    FULL_DIALOG_CLOSE: "FULL_DIALOG_CLOSE",
    NORMAL_DIALOG: "NORMAL_DIALOG",
    NORMAL_DIALOG_OPEN: "NORMAL_DIALOG_OPEN",
    NORMAL_DIALOG_CLOSE: "NORMAL_DIALOG_CLOSE",
    SNACKBAR: "SNACKBAR",
    SNACKBAR_OPEN: "SNACKBAR_OPEN",
    SNACKBAR_CLOSE: "SNACKBAR_CLOSE",
    CREATE_TREND: "CREATE_TREND",
    RESET_TREND: "RESET_TREND",
    //ADDED
    CREATE_ADD_REPORT: "CREATE_ADD_REPORT",
    RESET_ADD_REPORT: "RESET_ADD_REPORT",

    CREATE_SCHEDULE: 'CREATE_SCHEDULE',
    RESET_SCHEDULE: 'RESET_SCHEDULE',
    LOGIN_DETAILS: "LOGIN_DETAILS",
    LOGOUT_DETAILS: "LOGOUT_DETAILS",
    GLOBAL_SETTINGS: 'GLOBAL_SETTINGS',
    REPORT_DETAILS: 'REPORT_DETAILS',
    SET_REGEX : 'SET_REGEX'
}
export default Constants;